server:
  port: 8468
logging:
  file: /java/C2S_LOGS/master-ui-api/masterUiApi.log
info:
  component: MASTER UI API
ribbon:
  ReadTimeout: 50000
hystrix.command.default.execution.timeout.enabled: false
security:
  oauth2:
    client:
      client-id:  master-ui-api
c2s:
  master-ui:
      mapping:
        patient:
          client-id: c2s-ui
          client-secret: changeit
          access-scope: c2sUi.access
          home-url: ${c2s.c2s-ui.context-path}/home
        provider:
          client-id: provider-ui
          client-secret: changeit
          access-scope: providerUi.access
          home-url: ${c2s.provider-ui.context-path}/home
        staff:
          client-id: staff-ui
          client-secret: changeit
          access-scope: staffUi.access
          home-url: ${c2s.staff-ui.context-path}/home
      login-url: ${c2s.master-ui.context-path}/login
  authorization-server:
      url: http://localhost/uaa
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /master-ui-api